# Generated by Django 3.2.9 on 2023-07-22 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=50, verbose_name='Note Başlığı')),
                ('note_content', models.TextField(max_length=400, verbose_name='Not İçeriği')),
                ('note_image', models.FileField(upload_to='uploads', verbose_name='Not Resmi')),
                ('note_url', models.URLField(verbose_name='Note Url')),
                ('note_createdat', models.DateTimeField(auto_now=True, verbose_name='Oluşturulma zamanı')),
                ('noteauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
    ]
