# Generated by Django 3.2.9 on 2023-07-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.FileField(upload_to='uplods/logo', verbose_name='Logo')),
            ],
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_image',
            field=models.FileField(blank=True, upload_to='uplods/blog', verbose_name='Not Resmi'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_url',
            field=models.URLField(blank=True, verbose_name='Note Url'),
        ),
    ]
