# Generated by Django 3.2.9 on 2023-07-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0002_auto_20230725_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note_url',
            field=models.URLField(blank=True, null=True, verbose_name='Note Url'),
        ),
    ]
