# Generated by Django 3.2.9 on 2023-07-30 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dj_app', '0004_notes_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='banned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sebep', models.CharField(max_length=200, verbose_name='Sebebi')),
                ('tarih', models.DateTimeField(auto_now=True, verbose_name='Banlanma Zamanı')),
                ('authorized', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kim banladı')),
                ('banneduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banneduser', to=settings.AUTH_USER_MODEL, verbose_name='Banlanan kişi')),
            ],
        ),
    ]
