# Generated by Django 3.2.9 on 2023-07-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0005_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='notsil',
            field=models.BooleanField(default=False, help_text='Kullanıcı Notu Silebilirmi', verbose_name='Notu Silebilirmi'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='approved',
            field=models.BooleanField(default=False, help_text='Not Onaylandımı ?', verbose_name='Onay Aşaması'),
        ),
    ]
