# Generated by Django 3.2.9 on 2023-07-30 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0006_auto_20230730_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='notsil',
        ),
        migrations.CreateModel(
            name='notsilonay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notsil', models.BooleanField(default=False, help_text='Kullanıcı Notu Silebilirmi', verbose_name='Notu Silebilirmi')),
                ('usernot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_app.notes', verbose_name='Notu')),
            ],
        ),
    ]
