# Generated by Django 3.2.9 on 2023-07-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0007_auto_20230730_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='notsil',
            field=models.BooleanField(default=False, help_text='Kullanıcı Notu Silebilirmi', verbose_name='Notu Silebilirmi'),
        ),
        migrations.DeleteModel(
            name='notsilonay',
        ),
    ]
